# This workflow will build and push a Python application to an Azure Web App when a commit is pushed to your default branch.
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App from the Overview page in the Azure Portal.
# 2. Create a repository secret named AZURE_WEBAPP_PUBLISH_PROFILE and paste the publish profile as its value.
# 3. Set the AZURE_WEBAPP_NAME below to match your Azure Web App name.
# 4. In Azure App Service > Configuration > General settings, set the Startup Command to:
#       gunicorn -w 4 -k uvicorn.workers.UvicornWorker ucanrr1_api_with_roles_azure:app

name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: analyzeapi  # set this to the name of your Azure Web App
  PYTHON_VERSION: '3.11'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !antenv/

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
